from sqlalchemy import Column, Integer, String, Boolean, DECIMAL
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class RegistroINM(Base):
    __tablename__ = "inm"

    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer)
    periodo = Column(String(6))
    uf = Column(String(2))
    cfop = Column(String(4))
    cfop_transferencia = Column(String(4))
    bc_icms = Column(DECIMAL(15, 2))
    aliq_icms = Column(DECIMAL(5, 2))
    vl_icms = Column(DECIMAL(15, 2))
    vl_icms_isentas = Column(DECIMAL(15, 2))
    vl_icms_outras = Column(DECIMAL(15, 2))
    bc_ipi = Column(DECIMAL(15, 2))
    vl_ipi = Column(DECIMAL(15, 2))
    vl_ipi_isentas = Column(DECIMAL(15, 2))
    vl_ipi_outras = Column(DECIMAL(15, 2))
    subst_icms = Column(String(1))
    subst_ipi = Column(String(1))
    subst_cofins = Column(String(1))
    subst_pis = Column(String(1))
    cst_a = Column(String(2))
    cst_b = Column(String(2))
    cst_pis = Column(String(2))
    cst_cofins = Column(String(2))
    cst_ipi = Column(String(2))
    csosn = Column(String(3))
    mono_cofins = Column(String(1))
    mono_pis = Column(String(1))
    calc_fecop = Column(String(1))
    aliq_subst = Column(DECIMAL(5, 2))
    bc_fcp = Column(DECIMAL(15, 2))
    aliq_fcp = Column(DECIMAL(5, 2))
    vl_fcp = Column(DECIMAL(15, 2))
    bc_fcp_st = Column(DECIMAL(15, 2))
    aliq_fcp_st = Column(DECIMAL(5, 2))
    vl_fcp_st = Column(DECIMAL(15, 2))
    aliq_icms_diferimento = Column(DECIMAL(5, 2))
    ativo = Column(Boolean, default=True)
