from sqlalchemy import Column, Integer, String, Boolean, Date, DECIMAL, Text
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class RegistroNFM(Base):
    __tablename__ = "nfm"

    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, nullable=False)
    periodo = Column(String(6), nullable=False)
    cod_part = Column(String(60))
    operacao = Column(String(1))
    especie = Column(String(5))
    doc_proprio = Column(String(1))
    numero = Column(String(9))
    serie = Column(String(3))
    subserie = Column(String(3))
    aidf = Column(String(25))
    formulario_ini = Column(String(6))
    formulario_fin = Column(String(6))
    data_emissao = Column(Date)
    data_entrada = Column(Date)
    situacao = Column(String(1))
    vl_prod = Column(DECIMAL(15, 2))
    vl_frt = Column(DECIMAL(15, 2))
    vl_seg = Column(DECIMAL(15, 2))
    outras_despesas = Column(DECIMAL(15, 2))
    vl_ipi = Column(DECIMAL(15, 2))
    vl_icms_st = Column(DECIMAL(15, 2))
    vl_serv_iss = Column(DECIMAL(15, 2))
    vl_desc = Column(DECIMAL(15, 2))
    vl_total = Column(DECIMAL(15, 2))
    qtd_itens = Column(Integer)
    base_cofins = Column(DECIMAL(15, 2))
    base_pis = Column(DECIMAL(15, 2))
    base_csl1 = Column(DECIMAL(15, 2))
    base_csl2 = Column(DECIMAL(15, 2))
    base_irpj1 = Column(DECIMAL(15, 2))
    base_irpj2 = Column(DECIMAL(15, 2))
    base_irpj3 = Column(DECIMAL(15, 2))
    base_irpj4 = Column(DECIMAL(15, 2))
    ret_cofins = Column(DECIMAL(15, 2))
    ret_pis = Column(DECIMAL(15, 2))
    ret_csl = Column(DECIMAL(15, 2))
    ret_irpj = Column(DECIMAL(15, 2))
    gnre_vinculada = Column(String(1))
    tipo_icms = Column(String(1))
    mes_ano = Column(String(6))
    protocolo = Column(String(30))
    venc_gnre = Column(Date)
    recolhimento_gnre = Column(Date)
    banco_gnre = Column(String(24))
    agencia_gnre = Column(String(10))
    dv_gnre = Column(String(2))
    gnre_autenticada = Column(String(20))
    chave = Column(String(44))
    subst_recolher = Column(String(1))
    antecip_recolher = Column(String(1))
    difal_recolher = Column(String(1))
    subst_base = Column(String(1))
    base_subst = Column(DECIMAL(15, 2))
    vl_antecip = Column(DECIMAL(15, 2))
    iss_retido = Column(String(1))
    dt_ret_iss = Column(Date)
    servico = Column(String(2))
    dt_entrada_uf = Column(Date)
    frete_por_conta = Column(String(1))
    tipo_fatura = Column(String(1))
    eec = Column(String(6))
    cupom = Column(String(9))
    gera_transf = Column(String(1))
    obs = Column(Text)
    aliq_subst = Column(DECIMAL(5, 2))
    inss = Column(DECIMAL(15, 2))
    base_nao_cumul = Column(DECIMAL(15, 2))
    motivo_canc = Column(String(100))
    natureza = Column(String(2))
    codigo_info = Column(String(2))
    info_complementar = Column(Text)
    hora_saida = Column(String(8))
    uf_embarque = Column(String(2))
    local_embarque = Column(String(100))
    cod_contabil = Column(String(15))
    nfe_ref = Column(String(44))
    info_adicional = Column(Text)
    ind_consumidor = Column(String(1))
    presenca_comp = Column(String(1))
    dt_contingencia = Column(Date)
    hora_contingencia = Column(String(8))
    reconhece_nfe = Column(String(1))
    informada_pelo_contribuinte = Column(String(1))
    icms_desonerado = Column(DECIMAL(15, 2))
    prestador_servico = Column(String(1))
    cno = Column(String(15))
    dt_escrituracao = Column(Date)
    fcp_subst = Column(DECIMAL(15, 2))
    nfe_terceiro = Column(String(1))
    ativo = Column(Boolean, default=True)
